### ISSUE TITLE
Error on Win10 Pro / 1803 : An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.

### ISSUE THREAD

**Issue by awrog** [xmlexplorer/windows#1]
Really nice and fast tool!
After starting the app the following (non-blocking) error is shown....

```System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.Net.DownloadDataCompletedEventArgs.get_Result()
   at XmlExplorer.Controls.TabbedXmlExplorerWindow.OnDownloadDataCompleted(Object sender, DownloadDataCompletedEventArgs e) in C:\Source\Misc\XmlExplorer\XmlExplorer.Controls\TabbedXmlExplorerWindow.cs:line 1677```

**Comment by WFDexter** [comment]
I'm seeing this as well on program startup. Wonder if program tries to reach out to server at startup and is unable to do so?

Windows 10 Enterprise, Version 10.0.15063 Build 15063.

**Comment by mpryvkin** [comment]
XML Explorer tries to check for updates and fails. To avoid seeing this error, edit `XmlExplorer.exe.config`, find `CheckForUpdates` setting and change it to `False`, see below:

````
<setting name="CheckForUpdates" serializeAs="String">
    <value>False</value>
</setting>
````

**Comment by fhaag** [comment]
It should be noted that there may be several `CheckForUpdates` settings in the file; it only suppressed the update check for me after changing all of them to `False`.

**Comment by jasoncoon** [comment]
Sorry, I'll try to get this fixed soon.
